### ISSUE TITLE
Table of contents depth

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/recipes#14]
At the moment this is set at 2, which just gives major section headings. 3 would give more indication of what the various recipes cover (some of the section headings don't give much clue), but a more verbose table of contents. Any views on which is better?

**Comment by aradi** [comment]
I currently prefer 2. Setting it on 3 would expose a lot of irrelevant details (e.g. `Providing the input` in the first calculation section...).

The only thing, which I am missing from the TOC currently is the NEB-section, which does not appear there as it is a subsubsection. Probably, we should make  a full top level section on "Barrier height search" (or similar), make NEB a subsection where we just refer to the current subsubsection.
